<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="14.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Loyeris.IdentityAccess.Core\Loyeris.IdentityAccess.Core.csproj" />
      <ProjectReference Include="..\Loyeris.Shared\Loyeris.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Commands\" />
    </ItemGroup>

</Project>
