// <auto-generated />
using System;
using Loyeris.RentCollection.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Loyeris.RentCollection.Infrastructure.Migrations
{
    [DbContext(typeof(RentCollectionDbContext))]
    partial class RentCollectionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("collection")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Loyeris.RentCollection.Core.Entities.RentDeadline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChargesCents")
                        .HasColumnType("bigint")
                        .HasColumnName("charges_cents");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DueOn")
                        .HasColumnType("date")
                        .HasColumnName("due_on");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<long>("PaidCents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("paid_cents");

                    b.Property<DateOnly>("PeriodMonth")
                        .HasColumnType("date")
                        .HasColumnName("period_month");

                    b.Property<long>("RemainingCents")
                        .HasColumnType("bigint")
                        .HasColumnName("remaining_cents");

                    b.Property<long>("RentExcludingChargesCents")
                        .HasColumnType("bigint")
                        .HasColumnName("rent_excluding_charges_cents");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<long>("TotalDueCents")
                        .HasColumnType("bigint")
                        .HasColumnName("total_due_cents");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("DueOn", "Status");

                    b.HasIndex("LeaseId", "PeriodMonth")
                        .IsUnique();

                    b.HasIndex("PeriodMonth", "Status");

                    b.ToTable("rent_deadlines", "collection");
                });

            modelBuilder.Entity("Loyeris.RentCollection.Core.Entities.RentPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("method");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateOnly>("PaidOn")
                        .HasColumnType("date")
                        .HasColumnName("paid_on");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("reference");

                    b.Property<Guid>("RentDeadlineId")
                        .HasColumnType("uuid")
                        .HasColumnName("rent_deadline_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PaidOn")
                        .IsDescending();

                    b.HasIndex("RentDeadlineId", "PaidOn");

                    b.ToTable("rent_payments", "collection");
                });

            modelBuilder.Entity("Loyeris.RentCollection.Core.Entities.RentReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("recipient_email");

                    b.Property<Guid>("RentDeadlineId")
                        .HasColumnType("uuid")
                        .HasColumnName("rent_deadline_id");

                    b.Property<DateTimeOffset?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Scheduled")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("RentDeadlineId");

                    b.HasIndex("Status", "ScheduledFor");

                    b.ToTable("rent_reminders", "collection");
                });

            modelBuilder.Entity("Loyeris.RentCollection.Core.Entities.RentPayment", b =>
                {
                    b.HasOne("Loyeris.RentCollection.Core.Entities.RentDeadline", "RentDeadline")
                        .WithMany("Payments")
                        .HasForeignKey("RentDeadlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentDeadline");
                });

            modelBuilder.Entity("Loyeris.RentCollection.Core.Entities.RentReminder", b =>
                {
                    b.HasOne("Loyeris.RentCollection.Core.Entities.RentDeadline", "RentDeadline")
                        .WithMany("Reminders")
                        .HasForeignKey("RentDeadlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentDeadline");
                });

            modelBuilder.Entity("Loyeris.RentCollection.Core.Entities.RentDeadline", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
