# syntax=docker/dockerfile:1.7

FROM node:26-alpine
WORKDIR /app

RUN corepack enable && corepack prepare yarn@1.22.22 --activate
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --non-interactive

COPY . .

EXPOSE 4200

CMD ["yarn", "ng", "serve", "--host", "0.0.0.0", "--poll", "1000", "--proxy-config", "proxy.docker.conf.json"]
